

const f = () =>{
    try {
        console.log(Harry);
        console.log("Program ran successfully !!")
    }
    catch (e) {
        console.log(e)
    }
    finally {
        console.log("This is from Finally Part !!")
    }
}
f()